# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=400)),
                ('lastname', models.TextField(max_length=400)),
                ('username', models.TextField(max_length=400)),
                ('password', models.TextField(max_length=300)),
            ],
        ),
    ]
